[theme]
primaryColor = "#29B5E8"
backgroundColor = "#0F1115"
secondaryBackgroundColor = "#1A1D21"
textColor = "#E8EAED"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
